.gitignore, README.md, pom.xml
**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
No
**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
feature
**What is the current behavior?** *(You can also link to an open issue here)*
this is the first version of PowSyBl starter POM
**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
(if any of the questions/checkboxes don't apply, please delete them entirely)
=> Initial version

README.md, pom.xml
**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
No
**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
feature
**What is the current behavior?** *(You can also link to an open issue here)*
We use PowSyBl dependencies 1.0.0 (Core 4.7.0)
We use PowSyBl dependencies 1.1.0 (Core 4.8.0)
**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
(if any of the questions/checkboxes don't apply, please delete them …
=> Migrate to PowSyBl dependencies 1.1.0 (Core 4.8.0)

README.md, pom.xml
No
release
1.2.0-SNAPSHOT
1.3.0-SNAPSHOT
=> Release 1.2.0

README.md, pom.xml
No
release
1.2.0-SNAPSHOT
1.3.0 (first commit) then 1.3.0-SNAPSHOT (second commit)
=> Prepare release 1.3.0

README.md, pom.xml
No
release
1.4.0-SNAPSHOT
2.0.0 and update README.md (first commit) then 2.1.0-SNAPSHOT (second commit)
=> Prepare release v2.0.0

README.md, pom.xml
No
release
2.1.0-SNAPSHOT
2022.0.0 and update README.md (first commit) then 2023.0.0-SNAPSHOT (second commit)
=> Prepare release v2022.0.0

README.md, pom.xml
No
release
2022.0.0-SNAPSHOT & powsybl-dependencies v2022.0.0
Bump to v2023.0.0, bump powsybl-dependencies to v2023.0.0, and update README.md
=> Prepare v2023.0.0 release

README.md, pom.xml
No
release
2023.1.0 & powsybl-dependencies v2023.1.0
Bump to v2023.2.1, bump powsybl-dependencies to v2023.2.1, and update README.md
=> Bump to v2023.2.1

README.md, pom.xml
**Does this PR already have an issue describing the problem?**
Feature
- Bump to v2023.3.0-SNAPSHOT
- Update documentation
=> Bump to v2023.3.0-SNAPSHOT

README.md, pom.xml
Prepare next release 2023.3.0
2023.3.0-SNAPSHOT version
2023.3.0 (first commit) then 2023.4.0-SNAPSHOT (2nd commit)
:warning: **DO NOT** squash the commits, merge with fast-forward locally
=> Prepare v2023.3.0 release

README.md, pom.xml
No
release
powsybl-dependencies v2023.3.0
Bump powsybl-dependencies to v2023.3.1, and update README.md
=> Bump dependencies to v2023.3.1

README.md, pom.xml
No
release
powsybl-dependencies v2023.3.1
Bump powsybl-dependencies to **v2023.3.3**, and update README.md
**Does this PR introduce a breaking change or deprecate an API?**
=> Bump dependencies to v2023.3.3

README.md, pom.xml
Prepare next release 2023.4.0
2023.4.0-SNAPSHOT version
2023.4.0 and README.md updated (first commit) then 2024.0.0-SNAPSHOT (2nd commit)
=> Prepare v2023.4.0 release

README.md, pom.xml
Prepare next release 2024.0.0
2024.0.0-SNAPSHOT version
2024.0.0 and README.md updated (first commit) then 2024.1.0-SNAPSHOT (2nd commit)
=> Prepare v2024.0.0 release

README.md, pom.xml
No
release
powsybl-dependencies v2024.0.0
Bump powsybl-dependencies to **v2024.0.1**, and update README.md
=> Bump dependencies to v2024.0.1

README.md, pom.xml
Prepare next release 2024.1.0
2024.1.0-SNAPSHOT version
2024.1.0 and README.md updated (first commit) then 2024.2.0-SNAPSHOT (2nd commit)
=> Prepare v2024.1.0 release

README.md, pom.xml
Prepare next release 2024.2.0
2024.2.0-SNAPSHOT version
2024.2.0 and README.md updated (first commit) then 2024.3.0-SNAPSHOT (2nd commit)
=> Prepare v2024.2.0 release

README.md, pom.xml
Prepare next release 2024.3.0
2024.3.0-SNAPSHOT version
2024.3.0 and README.md updated (first commit) then 2024.4.0-SNAPSHOT (2nd commit)
=> Prepare v2024.3.0 release

pom.xml
No
release
powsybl-dependencies v2024.3.0
Bump powsybl-dependencies to **v2024.3.1**
=> Bump dependencies to v2024.3.1

README.md, pom.xml
Prepare next release 2024.4.0
2024.4.0-SNAPSHOT version
2024.4.0 and README.md updated (first commit) then 2025.0.0-SNAPSHOT (2nd commit)
=> Prepare v2024.4.0 release

pom.xml
No
release
powsybl-dependencies v2024.4.0
Bump powsybl-dependencies to **v2024.4.1**
=> Bump dependencies to v2024.4.1

README.md
**Does this PR already have an issue describing the problem?**
No
Doc update
Last version in README.md is 2024.4.0.
Last version in README.md is **2024.4.1**.
**Does this PR introduce a breaking change or deprecate an API?**
=> Update README.md: v2024.4.1

pom.xml
No
release
powsybl-dependencies v2025.0.0
Bump powsybl-dependencies to **v2025.0.2**
=> Bump dependencies to v2025.0.2
